version: '3'
services:
  service_a:
    build: ./serviceA
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=<SUA_WEATHER_API_KEY>
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - service_b
      - otel-collector

  service_b:
    build: ./serviceB
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=<SUA_WEATHER_API_KEY>
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - "9411:9411"
